---
title: "Материалы"
output: 
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    theme: united
---
 
### Семинар 1 (9 сентября)
 
<a href="psy_seminar1_UPD.pdf" title=>Задания (UPD)</a>

<a href="psy_hw1_2020.pdf" title=>Домашнее задание 1</a>

<a href="psy_hw1_solution.pdf" title=>Решение дз 1 (дополнительные задачи)</a>

### Семинар 2 (16 сентября)

<a href="psy_seminar_2.pdf" title=>Задания </a>

Подготовка к проверочной работе: <a href="psy_hw2.pdf" title=>Домашнее задание 2</a>

К семинару 23 сентября: <a href="psy_hw3.pdf" title=>Домашнее задание 3 </a>

Мини-тест 1: 

<a href="psy2020_test1_1.pdf" title=>Вариант 1</a>

<a href="psy2020_test1_2.pdf" title=>Вариант 2</a>

<a href="psy2020_test1_3.pdf" title=>Вариант 3 </a>

### Семинар 3 (23 сентября)

К семинару 30 сентября: <a href="psy_hw4_2020.pdf" title=>Домашнее задание 4 </a>

### Семинар 4 (30 сентября)

<a href="psy_seminar4_2020.pdf" title=> Задания </a>

К семинару 7 октября (подготовка к проверочной работе №2): <a href="psy_hw5_2020.pdf" title=>Домашнее задание 5 </a>

Резюме: <a href="psy_LO1.pdf" title=> Learning outcomes №1 </a>

### Семинар 5 (7 октября)

<a href="psy_seminar5_2020.pdf" title=> Задания </a>

Домашнее задание: дорешать, что получится из оставшихся задач семинарского листка

<a href="stand_normal.pdf" title=> Таблица стандартного нормального распределения </a>

<a href="psy_EXEY.pdf" title=> Почему для независимых сл.в. EXY = EXEY? Подсказка </a>

Мини-тест 2: 

<a href="psy_test2_1.pdf" title=>Вариант 1</a>

<a href="psy_test2_2.pdf" title=>Вариант 2</a>

<a href="psy_test2_3.pdf" title=>Вариант 3 </a>

### Семинар 6

<a href="psy_seminar6_2020.pdf" title=>Семинар 6 </a>

### Семинар 7

<a href="psy_seminar7_2020.pdf" title=>Семинар 7 </a>

### Семинар 8

<a href="psy_seminar8_2020.pdf" title=>Семинар 8 </a>

<a href="Student-distribution.pdf" title=>Таблица распределения Стьюдента </a>

### Семинар 9

<a href="psy_seminar9_2020.pdf" title=>Семинар 9 </a>

<a href="psy_hw6_2020.pdf" title=>Домашнее задание </a>

<a href="psy_hypothesis_testing.pdf" title=> Презентация по логике проверки гипотез </a>

### Семинар 10

<a href="psy_seminar10_2020.pdf" title=>Семинар 10 </a>

<a href="psy_hw_solution.pdf" title=>Домашнее задание для тренировки с ответами</a>

Мини-тест 3: 

<a href="psy_test3_1.pdf" title=>Пример 1</a>

<a href="psy_test3_2.pdf" title=>Пример 2</a>

<a href="psy_test3_3.pdf" title=>Пример 3</a>

### Семинар 11

<a href="psy_seminar11.pdf" title=>Семинар 11 </a>

<a href="psy_hw8_2020.pdf" title=>Домашнее задание 8</a>

### Семинар 12

<a href="psy_seminar12.pdf" title=>Семинар 12 </a>

<a href="psy_hw9_2020.pdf" title=>Домашнее задание 9</a>

